name: binary_types
version: 0.0.47
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Binary types are set of classes that allows access the binary data in "C" language way.
homepage: https://github.com/mezoni/binary_types
dependencies:
  binary_declarations: any
  macro_processor: any
  system_info: any
  unsafe_extension: any
dev_dependencies:
  unittest: any
